apiVersion: v1
kind: Secret
metadata:
  name: ${BENCHMARK_RISINGWAVE_NAME}-minio-credentials
  namespace: ${BENCHMARK_NAMESPACE}
stringData:
  username: "${BENCHMARK_MINIO_CREDENTIALS_0_USERNAME}"
  password: "${BENCHMARK_MINIO_CREDENTIALS_0_PASSWORD}"
