[benchmark]
namespace = "benchmark-risingwave"

[benchmark.aws]
ask_before_proceed = false

[benchmark.aws.credentials]
access_key = ""
access_secret = ""

[benchmark.job]
type = "nexmark-kafka"
name = "benchmark-job"

[benchmark.job.resources]
cpu = { limit = "1", request = "500m" }
mem = { limit = "1Gi", request = "512Mi" }

[benchmark.job.wait]
retry_limit = 500
retry_interval = 10

[benchmark.pods.distribution]
mutual_exclusive_policy = "global"
mutual_exclusive_key = ""
compactor_compute_affinity_enabled = "true"

[benchmark.nexmark]
query = "q0"

[benchmark.nexmark_kafka]
max_events = 10000
generator_thread_num = 4
event_rate = 1000
partition = 1
keep_kafka_data = false
skip_insert_kafka = false
image_pull_policy = "IfNotPresent"
enable_blackhole = "false"
watermark = false

[benchmark.risingwave]
version = "v3.0.0"
meta_store = "postgresql"

[benchmark.risingwave.wait]
retry_limit = 60
retry_interval = 10

[benchmark.risingwave.replicas]
meta = 1
frontend = 1
compute = 1
compactor = 1
connector = 0

[benchmark.risingwave.resources]
cpu = { limit = "1", request = "500m" }
mem = { limit = "2Gi", request = "1Gi" }

[benchmark.risingwave.resources.compactor]
cpu = { limit = "1", request = "100m" }
mem = { limit = "1Gi", request = "256Mi" }

[benchmark.risingwave.resources.compute]
cpu = { limit = "2", request = "500m" }
mem = { limit = "2Gi", request = "1Gi" }

[benchmark.risingwave.compute.memory_profiling]
enable = "false"
lg_prof_interval = 40
lg_prof_sample = 19

[benchmark.risingwave.storage]
type = "minio"

[benchmark.risingwave.storage.minio]
bucket = "hummock"
data_directory = "hummock_001"

[benchmark.etcd.resources]
cpu = { limit = "1", request = "100m" }
mem = { limit = "1Gi", request = "256Mi" }

[benchmark.postgresql.metastore.resources]
cpu = { limit = "1", request = "100m" }
mem = { limit = "1Gi", request = "256Mi" }

[benchmark.postgresql.metastore.persistence]
enabled = true
storage_class = ""
size = "8Gi"

[benchmark.minio.resources]
cpu = { limit = "1", request = "100m" }
mem = { limit = "1Gi", request = "256Mi" }

[benchmark.minio.persistence]
enabled = true
storage_class = ""
size = "8Gi"

[benchmark.kafka]
enabled = true
keep_pod_enabled = false

[benchmark.kafka.resources]
cpu = { limit = "1", request = "500m" }
mem = { limit = "1Gi", request = "512Mi" }

[benchmark.kafka.persistence]
enabled = true
storage_class = ""
size = "8Gi"

[benchmark.kafka.zookeeper.persistence]
enabled = true
storage_class = ""

[benchmark.kafka.metrics]
jmx_enabled = false
servicemonitor_enabled = false
