# One can list the possible values with
#   helm show values bitnami/kafka

deleteTopicEnable: true

logRetentionBytes: _${BENCHMARK_KAFKA_LOG_RETENTION_BYTES}

logRetentionHours: ${BENCHMARK_KAFKA_LOG_RETENTION_HOURS}

resources:
  limits:
    cpu: ${BENCHMARK_KAFKA_RESOURCES_CPU_LIMIT}
    memory: ${BENCHMARK_KAFKA_RESOURCES_MEM_LIMIT}
  requests:
    cpu: ${BENCHMARK_KAFKA_RESOURCES_CPU_REQUEST}
    memory: ${BENCHMARK_KAFKA_RESOURCES_MEM_REQUEST}

persistence:
  enabled: ${BENCHMARK_KAFKA_PERSISTENCE_ENABLED}
  storageClass: ${BENCHMARK_KAFKA_PERSISTENCE_STORAGE_CLASS}
  size: ${BENCHMARK_KAFKA_PERSISTENCE_SIZE}

zookeeper:
  persistence:
    enabled: ${BENCHMARK_KAFKA_ZOOKEEPER_PERSISTENCE_ENABLED}
    storageClass: ${BENCHMARK_KAFKA_ZOOKEEPER_PERSISTENCE_STORAGE_CLASS}
  affinity: ${BENCHMARK_PODS_DISTRIBUTION_GEN_AFFINITY_ZK}

metrics:
  kafka:
    enabled: ${BENCHMARK_KAFKA_METRICS_KAFKA_ENABLED}
  jmx:
    enabled: ${BENCHMARK_KAFKA_METRICS_JMX_ENABLED}
  serviceMonitor:
    enabled: ${BENCHMARK_KAFKA_METRICS_SERVICEMONITOR_ENABLED}

podLabels:
  benchmark/system: kube-bench
  benchmark/mutual-exclusive-key: "${BENCHMARK_PODS_DISTRIBUTION_MUTUAL_EXCLUSIVE_KEY}"
  benchmark/pod-affinity: kafka

nodeSelector: ${BENCHMARK_PODS_DISTRIBUTION_GEN_NODE_SELECTOR}

affinity: ${BENCHMARK_PODS_DISTRIBUTION_GEN_AFFINITY}