[benchmark]
namespace = "benchmark-flink"
system = "flink"

[benchmark.aws]
ask_before_proceed = false

[benchmark.aws.credentials]
access_key = ""
access_secret = ""

[benchmark.job]
name = "benchmark-job"
type = "flink-nexmark-kafka"

[benchmark.job.resources]
cpu = { limit = "1", request = "500m" }
mem = { limit = "1Gi", request = "512Mi" }

[benchmark.job.wait]
retry_limit = 500
retry_interval = 10

[benchmark.pods.distribution]
mutual_exclusive_policy = "global"
mutual_exclusive_key = ""

## Kafka related variables.
[benchmark.kafka]
enabled = true
name = "benchmark-kafka"
keep_pod_enabled = false

[benchmark.nexmark]
query = "q0"

[benchmark.nexmark_kafka]
max_events = 10000
generator_thread_num = 4
event_rate = 1000
partition = 1
keep_kafka_data = false
skip_insert_kafka = false
image_pull_policy = "IfNotPresent"

[benchmark.kafka.resources]
cpu = { limit = "1", request = "500m" }
mem = { limit = "1Gi", request = "512Mi" }

[benchmark.kafka.persistence]
enabled = true
storage_class = ""
size = "8Gi"

[benchmark.kafka.zookeeper.persistence]
enabled = true
storage_class = ""

[benchmark.kafka.metrics]
jmx_enabled = false
servicemonitor_enabled = false

[benchmark.flink]
enabled = true
name = "benchmark-flink"
taskmanager_replicas = "1"
taskmanager_slots = "1"
parallelism = "1"
jobmanager_memory = "1G"
taskmanager_memory = "1G"
checkpoint_interval = 180000
image = { tag = "v1.16.0" }

[benchmark.flink.s3]
access_key = ""
access_secret = ""
bucket = "flink"
bucket_folder = "checkpoints"

[benchmark.flink.resources]
cpu = { limit = "1", request = "500m" }
mem = { limit = "1Gi", request = "512Mi" }

[benchmark.flink.persistence]
storage_class = ""
size = "100Gi"
